// AUTO-GENERATED by scripts/fetch_fonts.py. Do not edit.
//
// Font Awesome 6 Free Solid, merged into the UI font at startup, so an icon is
// just a string and goes anywhere text goes:
//
//     ImGui::Button(ICON_FA_GEAR "  设置");
//     state->island_icon = ICON_FA_BOLT;
//
// Codepoints are read out of the font's own cmap by glyph name when this file
// is generated, so they cannot drift from what is actually embedded.
#pragma once

// clang-format off
#define ICON_FA_HOUSE         "\xef\x80\x95"   // house U+F015
#define ICON_FA_GEAR          "\xef\x80\x93"   // gear U+F013
#define ICON_FA_SLIDERS       "\xef\x87\x9e"   // sliders U+F1DE
#define ICON_FA_GAUGE         "\xef\x8f\xbd"   // gauge-high U+F3FD
#define ICON_FA_LAYER_GROUP   "\xef\x97\xbd"   // layer-group U+F5FD
#define ICON_FA_GRID          "\xef\x80\x89"   // table-cells-large U+F009
#define ICON_FA_LIST          "\xef\x80\xba"   // list U+F03A
#define ICON_FA_BARS          "\xef\x83\x89"   // bars U+F0C9
#define ICON_FA_CIRCLE_INFO   "\xef\x81\x9a"   // circle-info U+F05A
#define ICON_FA_WINDOW        "\xef\x8b\x90"   // window-maximize U+F2D0
#define ICON_FA_PLAY          "\xef\x81\x8b"   // play U+F04B
#define ICON_FA_PAUSE         "\xef\x81\x8c"   // pause U+F04C
#define ICON_FA_STOP          "\xef\x81\x8d"   // stop U+F04D
#define ICON_FA_ARROW_ROTATE  "\xef\x80\x9e"   // arrow-rotate-right U+F01E
#define ICON_FA_PLUS          "\xef\x81\xa7"   // plus U+F067
#define ICON_FA_MINUS         "\xef\x81\xa8"   // minus U+F068
#define ICON_FA_XMARK         "\xef\x80\x8d"   // xmark U+F00D
#define ICON_FA_CHECK         "\xef\x80\x8c"   // check U+F00C
#define ICON_FA_PEN           "\xef\x8c\x84"   // pen U+F304
#define ICON_FA_TRASH         "\xef\x87\xb8"   // trash U+F1F8
#define ICON_FA_COPY          "\xef\x83\x85"   // copy U+F0C5
#define ICON_FA_DOWNLOAD      "\xef\x80\x99"   // download U+F019
#define ICON_FA_UPLOAD        "\xef\x82\x93"   // upload U+F093
#define ICON_FA_SHARE         "\xef\x87\xa0"   // share-nodes U+F1E0
#define ICON_FA_MAGNIFIER     "\xef\x80\x82"   // magnifying-glass U+F002
#define ICON_FA_POWER         "\xef\x80\x91"   // power-off U+F011
#define ICON_FA_CHEVRON_UP    "\xef\x81\xb7"   // chevron-up U+F077
#define ICON_FA_CHEVRON_DOWN  "\xef\x81\xb8"   // chevron-down U+F078
#define ICON_FA_CHEVRON_LEFT  "\xef\x81\x93"   // chevron-left U+F053
#define ICON_FA_CHEVRON_RIGHT "\xef\x81\x94"   // chevron-right U+F054
#define ICON_FA_ARROW_UP      "\xef\x81\xa2"   // arrow-up U+F062
#define ICON_FA_ARROW_DOWN    "\xef\x81\xa3"   // arrow-down U+F063
#define ICON_FA_ARROW_LEFT    "\xef\x81\xa0"   // arrow-left U+F060
#define ICON_FA_ARROW_RIGHT   "\xef\x81\xa1"   // arrow-right U+F061
#define ICON_FA_EXPAND        "\xef\x81\xa5"   // expand U+F065
#define ICON_FA_COMPRESS      "\xef\x81\xa6"   // compress U+F066
#define ICON_FA_CIRCLE_CHECK  "\xef\x81\x98"   // circle-check U+F058
#define ICON_FA_CIRCLE_XMARK  "\xef\x81\x97"   // circle-xmark U+F057
#define ICON_FA_TRIANGLE_WARN "\xef\x81\xb1"   // triangle-exclamation U+F071
#define ICON_FA_BELL          "\xef\x82\xa2"   // bell U+F0A2
#define ICON_FA_STAR          "\xef\x80\x85"   // star U+F005
#define ICON_FA_HEART         "\xef\x80\x84"   // heart U+F004
#define ICON_FA_BOLT          "\xef\x83\xa7"   // bolt U+F0E7
#define ICON_FA_FIRE          "\xef\x81\xad"   // fire U+F06D
#define ICON_FA_SPINNER       "\xef\x84\x90"   // spinner U+F110
#define ICON_FA_HOURGLASS     "\xef\x89\x92"   // hourglass-half U+F252
#define ICON_FA_MOBILE        "\xef\x8f\x8f"   // mobile-screen U+F3CF
#define ICON_FA_DESKTOP       "\xef\x84\x88"   // desktop U+F108
#define ICON_FA_MICROCHIP     "\xef\x8b\x9b"   // microchip U+F2DB
#define ICON_FA_MEMORY        "\xef\x94\xb8"   // memory U+F538
#define ICON_FA_BATTERY       "\xef\x89\x81"   // battery-three-quarters U+F241
#define ICON_FA_WIFI          "\xef\x87\xab"   // wifi U+F1EB
#define ICON_FA_SIGNAL        "\xef\x80\x92"   // signal U+F012
#define ICON_FA_TOWER         "\xef\x94\x99"   // tower-broadcast U+F519
#define ICON_FA_VOLUME        "\xef\x80\xa8"   // volume-high U+F028
#define ICON_FA_VOLUME_MUTE   "\xef\x9a\xa9"   // volume-xmark U+F6A9
#define ICON_FA_CAMERA        "\xef\x80\xb0"   // camera U+F030
#define ICON_FA_VIDEO         "\xef\x80\xbd"   // video U+F03D
#define ICON_FA_IMAGE         "\xef\x80\xbe"   // image U+F03E
#define ICON_FA_FILE          "\xef\x80\x96"   // file U+F016
#define ICON_FA_FOLDER        "\xef\x81\xbb"   // folder U+F07B
#define ICON_FA_DATABASE      "\xef\x87\x80"   // database U+F1C0
#define ICON_FA_CLOCK         "\xef\x80\x97"   // clock U+F017
#define ICON_FA_CALENDAR      "\xef\x84\xb3"   // calendar U+F133
#define ICON_FA_USER          "\xef\x80\x87"   // user U+F007
#define ICON_FA_LOCK          "\xef\x80\xa3"   // lock U+F023
#define ICON_FA_UNLOCK        "\xef\x8f\x81"   // lock-open U+F3C1
#define ICON_FA_EYE           "\xef\x81\xae"   // eye U+F06E
#define ICON_FA_EYE_SLASH     "\xef\x81\xb0"   // eye-slash U+F070
#define ICON_FA_PALETTE       "\xef\x94\xbf"   // palette U+F53F
#define ICON_FA_DROPLET       "\xef\x81\x83"   // droplet U+F043
#define ICON_FA_SUN           "\xef\x86\x85"   // sun U+F185
#define ICON_FA_MOON          "\xef\x86\x86"   // moon U+F186
#define ICON_FA_WAND          "\xee\x8b\x8a"   // wand-magic-sparkles U+E2CA
#define ICON_FA_CUBE          "\xef\x86\xb2"   // cube U+F1B2
#define ICON_FA_ROBOT         "\xef\x95\x84"   // robot U+F544
#define ICON_FA_COMMENT       "\xef\x81\xb5"   // comment U+F075
#define ICON_FA_PAPER_PLANE   "\xef\x87\x98"   // paper-plane U+F1D8
#define ICON_FA_TERMINAL      "\xef\x84\xa0"   // terminal U+F120
#define ICON_FA_CODE          "\xef\x84\xa1"   // code U+F121
#define ICON_FA_LINK          "\xef\x83\x81"   // link U+F0C1
#define ICON_FA_ROTATE        "\xef\x8b\xb1"   // rotate U+F2F1
#define ICON_FA_THUMBTACK     "\xef\x82\x8d"   // thumbtack U+F08D
// clang-format on
